FROM python:3.7-alpine

RUN pip3 install paho-mqtt pika
RUN apk update && apk add bash
COPY src/ /app
WORKDIR /app
# CMD [ "python", "./MQTTPythonReferenceAgent.py" ]
CMD [ "python", "./MQTTRMQRelay.py" ]
